# -*- coding: utf-8 -*-
"""Model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13xGtEE2-9GbA4nN7VCVA8lmN1LmXCJdq
"""

class Model(nn.Module):
  def __init__(self):
    super().__init__()
    self.cnn1 = nn.Conv2d(in_channels=3,out_channels=32,kernel_size=3,stride=1,padding=1)
    self.cnn2= nn.Conv2d(in_channels=32,out_channels=64,kernel_size=3,stride=1,padding=1) 

    self.fc1= nn.Linear(18496,128)
    self.fc2= nn.Linear(128,10)

  def forward(self, x):
    x = F.relu(self.cnn1(x))
    x = F.max_pool2d(x, kernel_size=(2,2))
    x = F.relu(self.cnn2(x))
    x = F.max_pool2d(x, kernel_size=(2,2))
    x = torch.flatten(x, start_dim=1)
    x= F.relu(self.fc1(x))
    x = torch.dropout(x,0.3,train=True)
    x = self.fc2(x)
    x = torch.softmax(x, dim=1)
    return x

